### ISSUE TITLE
Failed to download dswifi-0.4.2.tar.bz2

### ISSUE THREAD

**Issue by romainrichard** [devkitPro/dswifi#3]
Hi,

When running the install script for `devkitPro`, I just got the following error:
```
$ sudo /tmp/devkitpro/perl/devkitARMupdate.pl /usr/local/devkitpro
devkitARM Updater/Installer
Installing to /usr/local/devkitpro
Downloading update file...OK!
Update libgba with libgba-0.5.0.tar.bz2
  Downloading...OK!
Update libmirko with libmirko-0.9.7.tar.bz2
  Downloading...OK!
Update dswifi with dswifi-0.4.2.tar.bz2
  Downloading...Failed to download dswifi-0.4.2.tar.bz2
```

Looks like the issue is that there are no files here https://sourceforge.net/projects/devkitpro/files/dswifi/0.4.2/

**Comment by WinterMute** [comment]
Apologies. I was copying files from SF yesterday and accidentally managed to delete these. Reuploaded now.

**Comment by romainrichard** [comment]
No worries, thanks for fixing it!
