### ISSUE TITLE
Can't Init Wifi twice

### ISSUE THREAD

**Issue by Fewnity** [devkitPro/dswifi#7]
Hello,
I'm using the Wifi and the Nifi on my NDS game, but I have a problem :
To use Nifi I need to Init the Wifi with this : `Wifi_InitDefault(false)`
But to use the Wifi for online game, I need to init with this : `Wifi_InitDefault(WFC_CONNECT)`
If I'm using the Nifi for a party then try to use the Wifi for an online party, the Wifi can't connect to a web server. Looks like the Wifi cannot be initiated twice. Is there a function to "uninitiate" the Wifi and then reinitiate it after that? Thanks 🙂
(same problem with calling `Wifi_InitDefault(WFC_CONNECT)` twice, the wifi can't connect to a web server).

**Comment by sgstair** [comment]
You shouldn't be using `Wifi_InitDefault()` more than once - There is no teardown, and init does a lot of one-time setup things that can't be repeated.
There are functions to connect and disconnect from access points though.
See `Wifi_DisconnectAP()` and `Wifi_AutoConnect()`

**Comment by Fewnity** [comment]
> You shouldn't be using `Wifi_InitDefault()` more than once. See `Wifi_DisconnectAP()` and `Wifi_AutoConnect()`

It's not fixing the issue, how I can Switch from Nifi mode to Wifi mode without calling Init function?
