### ISSUE TITLE
Using as dynamic library in existing ROM (mod)

### ISSUE THREAD

**Issue by axel7083** [devkitPro/dswifi#8]
I would like to know if it would be possible to use dswifi features in an existing ROM.

**Comment by sgstair** [comment]
I'm assuming that you mean hacking the dswifi library into a ROM that doesn't include it.
Probably challenging to say the least; the library in its current form touches quite a lot on both ARM7 and ARM9, and also relies on message passing through the FIFO. If its resources/interrupts aren't being trampled on, memory can be provided for the ARM9 buffers, and an alternate message passing is provided, it could probably work, but getting there will take some effort.
Additionally, if you mean a ROM where another wifi implementation is present, it's likely also necessary to disconnect all of that and keep the system happy, and I don't remember how difficult that will be.

**Comment by axel7083** [comment]
Okey thanks for the details, that look like something very challenging indeed. The rom that I would like to add the support to is SM64DS it does not _really_ have a full wifi library capabilities like MKDS has, just some stuff for the download play mode.

**Comment by sgstair** [comment]
Sure, no problem
IIRC, commercial games do all have basically the same capabilities in the ARM7, so bringing in missing wifi code from other games with matching ARM7 on the ARM9 side may be a viable option. I would expect unused code is optimized out of the ARM9 side but maybe they didn't, and other library functions are present and just not being used. Either of those are likely to be much easier than bringing in the dswifi lib though.
